function sendAutomatedEmail(e) {
  var rowValues = e.values;

  var timestamp = rowValues[0];
  var userName = rowValues[1];
  var userEmail = rowValues[2];
  var resourceLink = rowValues[3];

  var subject = "Thank you for your submission, " + userName + "!";
  var body =
    "Hi " +
    userName +
    ",\n\n" +
    "Thank you for submitting your resource to our automation system.\n\n" +
    "Details Received:\n" +
    "- Resource: " +
    resourceLink +
    "\n" +
    "- Received at: " +
    timestamp +
    "\n\n" +
    "This is an automated response generated by Task 2 Apps Script.";

  MailApp.sendEmail(userEmail, subject, body);
}
